#############################################################################
# Makefile for building: TimeTracker
# Generated by qmake (2.01a) (Qt 4.7.0) on: ter mai 3 10:54:50 2011
# Project:  TimeTracker.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.0-debug/bin/qmake -spec /usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/opt/qtcreator-2.1.0/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/opt/qtcreator-2.1.0/share/qtcreator/qml/qmljsdebugger -o Makefile TimeTracker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.0-debug/include/QtCore -I/usr/local/Trolltech/Qt-4.7.0-debug/include/QtGui -I/usr/local/Trolltech/Qt-4.7.0-debug/include/QtXml -I/usr/local/Trolltech/Qt-4.7.0-debug/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.0-debug/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.0-debug/lib -lQtXml -L/usr/local/Trolltech/Qt-4.7.0-debug/lib -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.7.0-debug/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		preferenceswidget.cpp \
		projectwidget.cpp \
		trayiconcommand.cpp \
		preferences.cpp \
		project.cpp \
		timespan.cpp \
		createprojectdialog.cpp moc_mainwindow.cpp \
		moc_preferenceswidget.cpp \
		moc_projectwidget.cpp \
		moc_preferences.cpp \
		moc_project.cpp \
		moc_createprojectdialog.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		mainwindow.o \
		preferenceswidget.o \
		projectwidget.o \
		trayiconcommand.o \
		preferences.o \
		project.o \
		timespan.o \
		createprojectdialog.o \
		moc_mainwindow.o \
		moc_preferenceswidget.o \
		moc_projectwidget.o \
		moc_preferences.o \
		moc_project.o \
		moc_createprojectdialog.o \
		qrc_res.o
DIST          = /usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/include_source_dir.prf \
		TimeTracker.pro
QMAKE_TARGET  = TimeTracker
DESTDIR       = 
TARGET        = TimeTracker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_preferenceswidget.h ui_projectwidget.h ui_createprojectdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TimeTracker.pro  /usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.0-debug/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-4.7.0-debug/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.7.0-debug/lib/libQtGui.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/opt/qtcreator-2.1.0/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/opt/qtcreator-2.1.0/share/qtcreator/qml/qmljsdebugger -o Makefile TimeTracker.pro
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.0-debug/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-4.7.0-debug/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.7.0-debug/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.0-debug/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/opt/qtcreator-2.1.0/share/qtcreator/qml/qmljsdebugger QMLJSDEBUGGER_PATH=/opt/qtcreator-2.1.0/share/qtcreator/qml/qmljsdebugger -o Makefile TimeTracker.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TimeTracker1.0.0 || $(MKDIR) .tmp/TimeTracker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TimeTracker1.0.0/ && $(COPY_FILE) --parents mainwindow.h preferenceswidget.h projectwidget.h trayiconcommand.h preferences.h project.h timespan.h createprojectdialog.h .tmp/TimeTracker1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/TimeTracker1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp preferenceswidget.cpp projectwidget.cpp trayiconcommand.cpp preferences.cpp project.cpp timespan.cpp createprojectdialog.cpp .tmp/TimeTracker1.0.0/ && $(COPY_FILE) --parents mainwindow.ui preferenceswidget.ui projectwidget.ui createprojectdialog.ui .tmp/TimeTracker1.0.0/ && (cd `dirname .tmp/TimeTracker1.0.0` && $(TAR) TimeTracker1.0.0.tar TimeTracker1.0.0 && $(COMPRESS) TimeTracker1.0.0.tar) && $(MOVE) `dirname .tmp/TimeTracker1.0.0`/TimeTracker1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TimeTracker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_preferenceswidget.cpp moc_projectwidget.cpp moc_preferences.cpp moc_project.cpp moc_createprojectdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_preferenceswidget.cpp moc_projectwidget.cpp moc_preferences.cpp moc_project.cpp moc_createprojectdialog.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_preferenceswidget.cpp: preferenceswidget.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/moc $(DEFINES) $(INCPATH) preferenceswidget.h -o moc_preferenceswidget.cpp

moc_projectwidget.cpp: projectwidget.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/moc $(DEFINES) $(INCPATH) projectwidget.h -o moc_projectwidget.cpp

moc_preferences.cpp: preferences.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/moc $(DEFINES) $(INCPATH) preferences.h -o moc_preferences.cpp

moc_project.cpp: timespan.h \
		project.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/moc $(DEFINES) $(INCPATH) project.h -o moc_project.cpp

moc_createprojectdialog.cpp: createprojectdialog.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/moc $(DEFINES) $(INCPATH) createprojectdialog.h -o moc_createprojectdialog.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		images/clock.png \
		images/clock-off.png
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_preferenceswidget.h ui_projectwidget.h ui_createprojectdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_preferenceswidget.h ui_projectwidget.h ui_createprojectdialog.h
ui_mainwindow.h: mainwindow.ui \
		preferenceswidget.h \
		projectwidget.h
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_preferenceswidget.h: preferenceswidget.ui
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/uic preferenceswidget.ui -o ui_preferenceswidget.h

ui_projectwidget.h: projectwidget.ui
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/uic projectwidget.ui -o ui_projectwidget.h

ui_createprojectdialog.h: createprojectdialog.ui
	/usr/local/Trolltech/Qt-4.7.0-debug/bin/uic createprojectdialog.ui -o ui_createprojectdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		preferenceswidget.h \
		projectwidget.h \
		preferences.h \
		trayiconcommand.h \
		timespan.h \
		project.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

preferenceswidget.o: preferenceswidget.cpp preferenceswidget.h \
		ui_preferenceswidget.h \
		preferences.h \
		trayiconcommand.h \
		project.h \
		timespan.h \
		createprojectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferenceswidget.o preferenceswidget.cpp

projectwidget.o: projectwidget.cpp projectwidget.h \
		ui_projectwidget.h \
		project.h \
		timespan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectwidget.o projectwidget.cpp

trayiconcommand.o: trayiconcommand.cpp trayiconcommand.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trayiconcommand.o trayiconcommand.cpp

preferences.o: preferences.cpp preferences.h \
		trayiconcommand.h \
		project.h \
		timespan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o preferences.cpp

project.o: project.cpp project.h \
		timespan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o project.o project.cpp

timespan.o: timespan.cpp timespan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timespan.o timespan.cpp

createprojectdialog.o: createprojectdialog.cpp createprojectdialog.h \
		ui_createprojectdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createprojectdialog.o createprojectdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_preferenceswidget.o: moc_preferenceswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferenceswidget.o moc_preferenceswidget.cpp

moc_projectwidget.o: moc_projectwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_projectwidget.o moc_projectwidget.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_project.o: moc_project.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_project.o moc_project.cpp

moc_createprojectdialog.o: moc_createprojectdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createprojectdialog.o moc_createprojectdialog.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

